### ISSUE TITLE
Get keynote template

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/slides#1]
Create keynote template and add here to create `xaringan` version

- [x] font families and sizes (for level 1, level 2 headers, etc)
- [x] color schemes (html values)
- [x] section dividers, refs 
- [x] aspect ratio (16:9)
- [x] misc. branding

**Comment by jvcasillas** [comment]
@troettge there is a draft you can look at here: https://learnb4ss.github.io/slides/ex/

I still need to tweak the font sizes, but you get the idea.

**Comment by stefanocoretta** [comment]
I quite like it! I'm a bit skeptic about Helvetica, but I can live with it.

**Comment by jvcasillas** [comment]
Im not a fan either (Timo's pick), but i'm terrible at choosing fonts.
